# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: pretty-format-json
  - repo: https://github.com/asottile/dead
    rev: v1.3.0
    hooks:
      - id: dead
  - repo: git@github.com:Yelp/detect-secrets
    rev: v0.14.3
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: .*/tests/.*
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.8.3'
    hooks:
    -   id: flake8
  - repo: https://github.com/PyCQA/bandit
    rev: '1.6.2'
    hooks:
    - id: bandit

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.3.1  # Use the ref you want to point at
    hooks:
    - id: mdformat
      # optional
      additional_dependencies:
      - mdformat-tables
      - mdformat-black
  - repo: https://github.com/dmitri-lerko/pre-commit-docker-kustomize
    rev: 98029a7a9fabbb46d73c9105540bb04c19755b64
    hooks:
    -   id: kustomize
        name: kustomize-base
        args: [k8s/base]
        verbose: false
    -   id: kustomize
        name: kustomize-prod
        args: [k8s/prod]
        verbose: false
