apiVersion: batch/v1
kind: Job
metadata:
  name: tesla-collector
spec:
  template:
    spec:
      containers:
      - name: tesla-collector
        image: registry.thesniderpad.com/tesla:latest
        env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: credentials
              key: SECRET_USERNAME
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: SECRET_PASSWORD
        imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 4