apiVersion: batch/v1
kind: Job
metadata:
  name: tesla-collector
spec:
  template:
    spec:
      containers:
      - name: tesla-collector
        image: ghcr.io/davidasnider/tesla-collector/tesla:latest
        env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: credentials
              key: SECRET_USERNAME
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: SECRET_PASSWORD
        imagePullPolicy: IfNotPresent
      restartPolicy: Never
  backoffLimit: 4
