name: Validation Checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      # Gitleaks check for secrets
      - name: Gitleaks
        uses: zricethezav/gitleaks-action@v1.1.4

  testbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Set version tags
        id: prep
        run: |
          VERSION=pr-${{ github.event.number }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./src
          file: ./src/Dockerfile
          platforms: linux/amd64,linux/arm/v7
          push: false
          tags: |
            ghcr.io/davidasnider/tesla-collector/tesla:${VERSION}
